import Head from "next/head";
import MobileFirstSection from "../components/MobileFirstSection/MobileFirstSection";
import Me from "../components/Me/Me";

export default function Home() {
  return (
    <>
      <Head>
        <title>Murat Demir</title>
        <meta name="description" content="Generated by muratdem1r" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/background.jpg" as="image" />
        <link rel="preload" href="/me/1.png" as="image" />
        <link rel="preload" href="/me/2.png" as="image" />
        <link rel="preload" href="/me/3.png" as="image" />
        <link rel="preload" href="/me/4.png" as="image" />
        <link rel="preload" href="/me/5.png" as="image" />
        <link rel="preload" href="/me/6.png" as="image" />
        <link rel="preload" href="/me/7.png" as="image" />
        <link rel="preload" href="/me/8.png" as="image" />
        <link rel="preload" href="/me/9.png" as="image" />
        <link rel="preload" href="/me/10.png" as="image" />
        <link rel="preload" href="/me/11.png" as="image" />
        <link rel="preload" href="/me/12.png" as="image" />
        <link rel="preload" href="/me/13.png" as="image" />
        <link rel="preload" href="/me/14.png" as="image" />
        <link rel="preload" href="/me/15.png" as="image" />
        <link rel="preload" href="/me/16.png" as="image" />
        <link rel="preload" href="/me/17.png" as="image" />
        <link rel="preload" href="/me/18.png" as="image" />
        <link rel="preload" href="/me/19.png" as="image" />
        <link rel="preload" href="/me/20.png" as="image" />
        <link rel="preload" href="/me/21.png" as="image" />
        <link rel="preload" href="/me/22.png" as="image" />
        <link rel="preload" href="/me/23.png" as="image" />
        <link rel="preload" href="/me/24.png" as="image" />
        <link rel="preload" href="/me/25.png" as="image" />
        <link rel="preload" href="/me/26.png" as="image" />
        <link rel="preload" href="/me/27.png" as="image" />
      </Head>
      <div className="container mx-auto px-5 text-white">
        <Me />
      </div>
    </>
  );
}
